The ``7-base_geometry`` module
======================

-------------------

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()
>>> bg.integer_validator(True)
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator("como", "stas")
Traceback (most recent call last):
...
TypeError: como must be an integer

>>> bg = BaseGeometry()
>>> bg.integer_validator(2, None)
Traceback (most recent call last):
...
TypeError: 2 must be an integer


>>> bg = BaseGeometry()
>>> bg.integer_validator("a")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg = BaseGeometry()
>>> bg.integer_validator("a", "b")
Traceback (most recent call last):
...
TypeError: a must be an integer



>>> bg = BaseGeometry()
>>> bg.integer_validator(True, False)
Traceback (most recent call last):
...
TypeError: True must be an integer


>>> bg = BaseGeometry()
>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'


>>> bg = BaseGeometry()
>>> bg.integer_validator("holis", -1)
Traceback (most recent call last):
...
ValueError: holis must be greater than 0


>>> bg = BaseGeometry()
>>> bg.integer_validator('holis', None)
Traceback (most recent call last):
...
TypeError: holis must be an integer


>>> bg = BaseGeometry()
>>> bg.integer_validator(2.3)
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg = BaseGeometry()
>>> bg.integer_validator([1, 2, 3])
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg = BaseGeometry()
>>> bg.integer_validator({2 , 3, 4}, {1, 2, 4})
Traceback (most recent call last):
...
TypeError: {2, 3, 4} must be an integer


>>> bg = BaseGeometry()
>>> bg.integer_validator(__dict__)
Traceback (most recent call last):
...
NameError: name '__dict__' is not defined


>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented

>>> bg = BaseGeometry()
>>> bg.integer_validator("ds", {1})
Traceback (most recent call last):
...
TypeError: ds must be an integer